services:
  - type: web
    name: qualisense-ai
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run qualisense.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
